---
title: Gebruik een Collider met een Trigger
hero_image: images/banner.png
description: Gebruik een collider met 'Is Trigger' ingeschakeld
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Gebruik een Collider met 'Is Trigger' ingeschakeld
